### ISSUE TITLE
Add support for IE10

### ISSUE THREAD

**Issue by mteper** [usablica/label.css#1]
This looks great in Chrome, but has issues with IE10 (notably hover effects). It would be great if worked cross-browser.

Thank you!

**Comment by slavanga** [comment]
It's a bug in IE10.
The combination of :hover and pseudo elements (:before and :after) on the same selector is causing trouble.

Here are some possible solutions to fix that: http://stackoverflow.com/a/16017251
Generally transitions and animations on pseudo elements only work in Firefox 4.0+, Chrome 26+ and IE10+ at the moment.

**Comment by HoseinEmrani** [comment]
Label.css has a little bugs in MAC Saffari and IE10 on hover effects. Thank you for report and solution. I'll fix it soon.
