### ISSUE TITLE
Conflicts with bootstrap

### ISSUE THREAD

**Issue by bjensen** [usablica/label.css#2]
Bootstrap also uses the label class. Perhaps you should consider changing the use of label to something else?

**Comment by HoseinEmrani** [comment]
It's my fault. bootstrap is a popular front end framework, I think it's better to change the label class name. I'll fix it soon. Thanks.

**Comment by bjensen** [comment]
I think this ticket should be reopened as it still has not been fixed and it is prohibiting a lot of bootstrap users from using this cool feature. 

@HoseinEmrani do you recommend people to create a fork of this repo to make it bootstrap compatible?

**Comment by arkmediastudio** [comment]
Same issue here, i can't use it with bootstrap because of class name conflict. @HoseinEmrani is there any bootstrap compatible fork?

**Comment by HoseinEmrani** [comment]
@bjensen I fix it one time, which class name has conflict?

**Comment by HoseinEmrani** [comment]
@bjensen Sorry! It was my fault. I've fixed it before and sync the changes just in `master` branch. `gh-pages` branch download link is now correct.
